Koenvh1/ets2-local-radio

web/lang/it-IT.json
I have updated the italian translation for the install-overlay string
=> Fixed install-overlay string

web/lang/it-IT.json
I have added my name as author ;)
=> Author Name Added

web/lang/ja-JP.json
=> Update Japanese translation

web/lang/it-IT.json
Added italian Translation to the new string (thanks for the mp, btw)
=> go-to-favorite-key

web/lang/be-BY.json
=> Updated be-BY

web/lang/ru-RU.json
Small fixes of the updated Ru translation
=> Small fixes

web/lang/it-IT.json
=> Missing String

web/lang/ru-RU.json
Broken station string translated and phrasing shortened
=> Ru-RU update

web/lang/be-BY.json
broken station string translated
=> Be-BY update

web/lang/pt-BR.json
Thanks for pointing it out Koenvh1
=> Fixed small typo, added untranslated line

web/cities/cities-ets2.js
A ridiculously minor edit but it confused me for a second when checking the configuration files - so saving other people the confusion :)
=> Correctly refer to The Great Steppe in cities-ets2

web/stations/images-europe/turkey/TRT Radyo 3.png
=> Create TRT Radyo 3.png

web/stations/stations-europe.js
TRT Radios and Radio Fenomen are fixed 
TRT Radyo 3 is added
=> update Turkish radios

web/stations/stations-europe.js
=> update TRT Radyo 3 logo

web/cities/cities-ats.js, web/stations/stations-america.js
Add support for Honolulu from the Island Map https://forum.scssoft.com/viewtopic.php?f=194&t=289493
=> Honolulu from Island map

web/stations/stations-europe.js
=> Poland fixes

README.md
Fixed broken link to redists 2010 and added link to redists 2012 which are often needed
=> Updated link and added another one in README.md

web/stations/stations-europe.js
Changed Radio Guerrilla's ( Romania, Europe ) url from a 48kb/s stream I previously submitted a form for to a 128kb/s stream.
=> Updated stations-europe.js: Radio Guerrilla's ( Romania, Europe ) url 48kbps to 128kbps

web/stations/stations-europe.js
I replaced abradio.cz streams since the abradio.cz server seems to be broken - the audio is laggy and has some problems.
=> Replaced abradio.cz streams

web/stations/stations-europe.js
Change the old flux for the new
=> Update The Melody Vintage Radio flux

web/cities/cities-ets2.js
=> Add a missing city in france

server/ETS2 Local Radio desktop/Main.cs, server/ETS2 Local Radio desktop/SimpleServer.cs, web/lib/js/main.js
Due to the issue mention in #256 and based on #257, this rewrites the /commands/ endpoint to server-side events to prevent the hibernation mode from interfering with the buttons.
=> Implement server side events for commands
